spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/salearninghub
spring.datasource.username=salearninghub_user
spring.datasource.password=devpassword123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true